// Code generated by protoc-gen-go. DO NOT EDIT.
// source: android/android.proto

/*
Package android is a generated protocol buffer package.

It is generated from these files:
	android/android.proto

It has these top-level messages:
	LoginRequest
	LoginReply
	GetConfigRequest
	GetConfigReply
	KeepaliveRequest
	KeepaliveReply
	GetProdectionListRequest
	Prodection
	GetProdectionListReply
	BuyTestRequest
	BuyTestReply
*/
package android

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

type LoginReply struct {
	Token       string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	ExpiresDate int64  `protobuf:"varint,2,opt,name=expiresDate" json:"expiresDate,omitempty"`
	Total       int64  `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Used        int64  `protobuf:"varint,4,opt,name=used" json:"used,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginReply) GetExpiresDate() int64 {
	if m != nil {
		return m.ExpiresDate
	}
	return 0
}

func (m *LoginReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *LoginReply) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type GetConfigRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetConfigRequest) Reset()                    { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()               {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetConfigRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetConfigReply struct {
	IP     string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	Method string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Passwd string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *GetConfigReply) Reset()                    { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string            { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()               {}
func (*GetConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetConfigReply) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *GetConfigReply) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *GetConfigReply) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetConfigReply) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type KeepaliveRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Rx    int64  `protobuf:"varint,2,opt,name=rx" json:"rx,omitempty"`
}

func (m *KeepaliveRequest) Reset()                    { *m = KeepaliveRequest{} }
func (m *KeepaliveRequest) String() string            { return proto.CompactTextString(m) }
func (*KeepaliveRequest) ProtoMessage()               {}
func (*KeepaliveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *KeepaliveRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *KeepaliveRequest) GetRx() int64 {
	if m != nil {
		return m.Rx
	}
	return 0
}

type KeepaliveReply struct {
	NeedStop    bool  `protobuf:"varint,1,opt,name=needStop" json:"needStop,omitempty"`
	ExpiresDate int64 `protobuf:"varint,2,opt,name=expiresDate" json:"expiresDate,omitempty"`
	Total       int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Used        int64 `protobuf:"varint,4,opt,name=used" json:"used,omitempty"`
}

func (m *KeepaliveReply) Reset()                    { *m = KeepaliveReply{} }
func (m *KeepaliveReply) String() string            { return proto.CompactTextString(m) }
func (*KeepaliveReply) ProtoMessage()               {}
func (*KeepaliveReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *KeepaliveReply) GetNeedStop() bool {
	if m != nil {
		return m.NeedStop
	}
	return false
}

func (m *KeepaliveReply) GetExpiresDate() int64 {
	if m != nil {
		return m.ExpiresDate
	}
	return 0
}

func (m *KeepaliveReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *KeepaliveReply) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

type GetProdectionListRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetProdectionListRequest) Reset()                    { *m = GetProdectionListRequest{} }
func (m *GetProdectionListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProdectionListRequest) ProtoMessage()               {}
func (*GetProdectionListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetProdectionListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type Prodection struct {
	ID    int64 `protobuf:"varint,1,opt,name=ID" json:"ID,omitempty"`
	Time  int64 `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
	Total int64 `protobuf:"varint,3,opt,name=total" json:"total,omitempty"`
	Price int64 `protobuf:"varint,4,opt,name=price" json:"price,omitempty"`
}

func (m *Prodection) Reset()                    { *m = Prodection{} }
func (m *Prodection) String() string            { return proto.CompactTextString(m) }
func (*Prodection) ProtoMessage()               {}
func (*Prodection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Prodection) GetID() int64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Prodection) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *Prodection) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Prodection) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type GetProdectionListReply struct {
	ProdectionList []*Prodection `protobuf:"bytes,1,rep,name=prodectionList" json:"prodectionList,omitempty"`
}

func (m *GetProdectionListReply) Reset()                    { *m = GetProdectionListReply{} }
func (m *GetProdectionListReply) String() string            { return proto.CompactTextString(m) }
func (*GetProdectionListReply) ProtoMessage()               {}
func (*GetProdectionListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetProdectionListReply) GetProdectionList() []*Prodection {
	if m != nil {
		return m.ProdectionList
	}
	return nil
}

type BuyTestRequest struct {
	Token        string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	ProdectionID int64  `protobuf:"varint,2,opt,name=prodectionID" json:"prodectionID,omitempty"`
}

func (m *BuyTestRequest) Reset()                    { *m = BuyTestRequest{} }
func (m *BuyTestRequest) String() string            { return proto.CompactTextString(m) }
func (*BuyTestRequest) ProtoMessage()               {}
func (*BuyTestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BuyTestRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *BuyTestRequest) GetProdectionID() int64 {
	if m != nil {
		return m.ProdectionID
	}
	return 0
}

type BuyTestReply struct {
	ExpiresDate int64 `protobuf:"varint,1,opt,name=expiresDate" json:"expiresDate,omitempty"`
	Total       int64 `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Used        int64 `protobuf:"varint,3,opt,name=used" json:"used,omitempty"`
}

func (m *BuyTestReply) Reset()                    { *m = BuyTestReply{} }
func (m *BuyTestReply) String() string            { return proto.CompactTextString(m) }
func (*BuyTestReply) ProtoMessage()               {}
func (*BuyTestReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *BuyTestReply) GetExpiresDate() int64 {
	if m != nil {
		return m.ExpiresDate
	}
	return 0
}

func (m *BuyTestReply) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BuyTestReply) GetUsed() int64 {
	if m != nil {
		return m.Used
	}
	return 0
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "android.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "android.LoginReply")
	proto.RegisterType((*GetConfigRequest)(nil), "android.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "android.GetConfigReply")
	proto.RegisterType((*KeepaliveRequest)(nil), "android.KeepaliveRequest")
	proto.RegisterType((*KeepaliveReply)(nil), "android.KeepaliveReply")
	proto.RegisterType((*GetProdectionListRequest)(nil), "android.GetProdectionListRequest")
	proto.RegisterType((*Prodection)(nil), "android.Prodection")
	proto.RegisterType((*GetProdectionListReply)(nil), "android.GetProdectionListReply")
	proto.RegisterType((*BuyTestRequest)(nil), "android.BuyTestRequest")
	proto.RegisterType((*BuyTestReply)(nil), "android.BuyTestReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Android service

type AndroidClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	Keepalive(ctx context.Context, in *KeepaliveRequest, opts ...grpc.CallOption) (*KeepaliveReply, error)
	GetProdectionList(ctx context.Context, in *GetProdectionListRequest, opts ...grpc.CallOption) (*GetProdectionListReply, error)
	BuyTest(ctx context.Context, in *BuyTestRequest, opts ...grpc.CallOption) (*BuyTestReply, error)
}

type androidClient struct {
	cc *grpc.ClientConn
}

func NewAndroidClient(cc *grpc.ClientConn) AndroidClient {
	return &androidClient{cc}
}

func (c *androidClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/android.Android/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *androidClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := grpc.Invoke(ctx, "/android.Android/GetConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *androidClient) Keepalive(ctx context.Context, in *KeepaliveRequest, opts ...grpc.CallOption) (*KeepaliveReply, error) {
	out := new(KeepaliveReply)
	err := grpc.Invoke(ctx, "/android.Android/Keepalive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *androidClient) GetProdectionList(ctx context.Context, in *GetProdectionListRequest, opts ...grpc.CallOption) (*GetProdectionListReply, error) {
	out := new(GetProdectionListReply)
	err := grpc.Invoke(ctx, "/android.Android/GetProdectionList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *androidClient) BuyTest(ctx context.Context, in *BuyTestRequest, opts ...grpc.CallOption) (*BuyTestReply, error) {
	out := new(BuyTestReply)
	err := grpc.Invoke(ctx, "/android.Android/BuyTest", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Android service

type AndroidServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	Keepalive(context.Context, *KeepaliveRequest) (*KeepaliveReply, error)
	GetProdectionList(context.Context, *GetProdectionListRequest) (*GetProdectionListReply, error)
	BuyTest(context.Context, *BuyTestRequest) (*BuyTestReply, error)
}

func RegisterAndroidServer(s *grpc.Server, srv AndroidServer) {
	s.RegisterService(&_Android_serviceDesc, srv)
}

func _Android_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AndroidServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/android.Android/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AndroidServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Android_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AndroidServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/android.Android/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AndroidServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Android_Keepalive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeepaliveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AndroidServer).Keepalive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/android.Android/Keepalive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AndroidServer).Keepalive(ctx, req.(*KeepaliveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Android_GetProdectionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProdectionListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AndroidServer).GetProdectionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/android.Android/GetProdectionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AndroidServer).GetProdectionList(ctx, req.(*GetProdectionListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Android_BuyTest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyTestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AndroidServer).BuyTest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/android.Android/BuyTest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AndroidServer).BuyTest(ctx, req.(*BuyTestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Android_serviceDesc = grpc.ServiceDesc{
	ServiceName: "android.Android",
	HandlerType: (*AndroidServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _Android_Login_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _Android_GetConfig_Handler,
		},
		{
			MethodName: "Keepalive",
			Handler:    _Android_Keepalive_Handler,
		},
		{
			MethodName: "GetProdectionList",
			Handler:    _Android_GetProdectionList_Handler,
		},
		{
			MethodName: "BuyTest",
			Handler:    _Android_BuyTest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "android/android.proto",
}

func init() { proto.RegisterFile("android/android.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x96, 0xed, 0xfe, 0x79, 0x5a, 0x45, 0xed, 0xb6, 0x69, 0x8d, 0xd5, 0x42, 0x58, 0x71, 0x88,
	0x2a, 0x51, 0x37, 0xcd, 0x05, 0x95, 0x13, 0x25, 0x52, 0x15, 0xe8, 0x21, 0x18, 0x38, 0x50, 0x21,
	0x24, 0x27, 0x5e, 0xdc, 0x55, 0x1d, 0xef, 0x62, 0xaf, 0x4b, 0x72, 0x84, 0x57, 0xe0, 0xd1, 0x78,
	0x05, 0x9e, 0x03, 0xa1, 0x5d, 0xff, 0xc4, 0x71, 0x43, 0xb8, 0x70, 0xf2, 0xce, 0xec, 0x37, 0xf3,
	0x7d, 0xb3, 0x33, 0x63, 0x68, 0x7a, 0x91, 0x1f, 0x33, 0xea, 0x3b, 0xf9, 0xf7, 0x84, 0xc7, 0x4c,
	0x30, 0xb4, 0x9e, 0x9b, 0xf6, 0x61, 0xc0, 0x58, 0x10, 0x12, 0xc7, 0xe3, 0xd4, 0xf1, 0xa2, 0x88,
	0x09, 0x4f, 0x50, 0x16, 0x25, 0x19, 0x0c, 0x63, 0xd8, 0xba, 0x62, 0x01, 0x8d, 0x5c, 0xf2, 0x25,
	0x25, 0x89, 0x40, 0x08, 0x56, 0xd2, 0x94, 0xfa, 0x96, 0xd6, 0xd2, 0xda, 0xa6, 0xab, 0xce, 0x38,
	0x02, 0xc8, 0x31, 0x3c, 0x9c, 0xa2, 0x3d, 0x58, 0x15, 0xec, 0x96, 0x44, 0x39, 0x24, 0x33, 0x50,
	0x0b, 0x36, 0xc9, 0x84, 0xd3, 0x98, 0x24, 0x3d, 0x4f, 0x10, 0x4b, 0x6f, 0x69, 0x6d, 0xc3, 0xad,
	0xba, 0xb2, 0x38, 0xe1, 0x85, 0x96, 0xa1, 0xee, 0x32, 0x43, 0xf1, 0x25, 0xc4, 0xb7, 0x56, 0x94,
	0x53, 0x9d, 0x71, 0x1b, 0xb6, 0x2f, 0x89, 0x78, 0xc9, 0xa2, 0xcf, 0x34, 0x28, 0x74, 0x2d, 0x64,
	0xc5, 0x3e, 0x34, 0x2a, 0x48, 0xa9, 0xae, 0x01, 0x7a, 0x7f, 0x90, 0x83, 0xf4, 0xfe, 0x40, 0xe6,
	0xe7, 0x2c, 0x16, 0x4a, 0x90, 0xe9, 0xaa, 0x33, 0xda, 0x87, 0xb5, 0x31, 0x11, 0x37, 0xcc, 0x57,
	0x52, 0x4c, 0x37, 0xb7, 0xa4, 0x9f, 0x7b, 0x49, 0xf2, 0x35, 0x53, 0x63, 0xba, 0xb9, 0x85, 0x9f,
	0xc1, 0xf6, 0x6b, 0x42, 0xb8, 0x17, 0xd2, 0x3b, 0xb2, 0x54, 0x8f, 0x64, 0x8f, 0x27, 0x79, 0xf1,
	0x7a, 0x3c, 0xc1, 0x13, 0x68, 0x54, 0x22, 0xa5, 0x3e, 0x1b, 0x36, 0x22, 0x42, 0xfc, 0xb7, 0x82,
	0x71, 0x15, 0xba, 0xe1, 0x96, 0xf6, 0x7f, 0x7d, 0xc3, 0x53, 0xb0, 0x2e, 0x89, 0x18, 0xc4, 0xcc,
	0x27, 0x23, 0xd9, 0xef, 0x2b, 0x9a, 0x88, 0xe5, 0x6f, 0xf9, 0x11, 0x60, 0x06, 0x57, 0xef, 0xd8,
	0x53, 0x00, 0xc3, 0xd5, 0xfb, 0x3d, 0xc9, 0x21, 0xe8, 0xb8, 0x10, 0xa5, 0xce, 0x7f, 0x51, 0xb3,
	0x07, 0xab, 0x3c, 0xa6, 0x23, 0x92, 0xcb, 0xc9, 0x0c, 0xfc, 0x1e, 0xf6, 0x17, 0xe8, 0x91, 0x2f,
	0xf2, 0x1c, 0x1a, 0x7c, 0xce, 0x6d, 0x69, 0x2d, 0xa3, 0xbd, 0x79, 0xb6, 0x7b, 0x52, 0x0c, 0xf4,
	0x2c, 0xca, 0xad, 0x41, 0xf1, 0x2b, 0x68, 0x5c, 0xa4, 0xd3, 0x77, 0xe4, 0x1f, 0xc5, 0x21, 0x0c,
	0x5b, 0xb3, 0xc8, 0x7e, 0x2f, 0x2f, 0x63, 0xce, 0x87, 0xaf, 0x61, 0xab, 0xcc, 0x25, 0x85, 0xd5,
	0xda, 0xa1, 0x2d, 0x69, 0x87, 0xbe, 0xa8, 0x1d, 0xc6, 0xac, 0x1d, 0x67, 0xbf, 0x0d, 0x58, 0x7f,
	0x91, 0x95, 0x83, 0xde, 0xc0, 0xaa, 0x5a, 0x27, 0xd4, 0x2c, 0x2b, 0xac, 0xae, 0xa0, 0xbd, 0x5b,
	0x77, 0xf3, 0x70, 0x8a, 0x0f, 0xbf, 0xff, 0xfc, 0xf5, 0x43, 0xdf, 0xc7, 0x3b, 0xce, 0x5d, 0xa7,
	0xd8, 0x74, 0x27, 0x94, 0xf7, 0xe7, 0xda, 0x31, 0xfa, 0x04, 0x66, 0xb9, 0x07, 0xe8, 0x41, 0x19,
	0x5f, 0xdf, 0x22, 0xfb, 0x60, 0xd1, 0x95, 0x4c, 0x7f, 0xa4, 0xd2, 0x1f, 0x60, 0x54, 0x4d, 0x3f,
	0x52, 0x00, 0x99, 0xdf, 0x03, 0xb3, 0x9c, 0xe3, 0x4a, 0xfe, 0xfa, 0x56, 0x54, 0xf2, 0xcf, 0x8f,
	0x3d, 0x6e, 0xa9, 0xfc, 0x36, 0x6e, 0x56, 0xf3, 0xdf, 0x16, 0x18, 0x49, 0xf1, 0x4d, 0x83, 0x9d,
	0x7b, 0x13, 0x82, 0x1e, 0x57, 0x05, 0x2f, 0x9c, 0x66, 0xfb, 0xd1, 0x32, 0x88, 0xe4, 0x6e, 0x2b,
	0x6e, 0x8c, 0x8f, 0xaa, 0xdc, 0x41, 0x1d, 0x2b, 0x35, 0x7c, 0x80, 0xf5, 0x7c, 0x02, 0xd0, 0xac,
	0x92, 0xf9, 0xf9, 0xb2, 0x9b, 0xf7, 0x2f, 0x24, 0xc9, 0x43, 0x45, 0x62, 0xe1, 0xdd, 0x2a, 0xc9,
	0x30, 0x43, 0x9c, 0x6b, 0xc7, 0x17, 0x4f, 0xae, 0x71, 0x40, 0xc5, 0x4d, 0x3a, 0x3c, 0x19, 0xb1,
	0xb1, 0x93, 0x9e, 0x76, 0x4f, 0x3b, 0xdd, 0x4e, 0xe7, 0xcc, 0x49, 0x92, 0xa7, 0x7c, 0x58, 0x04,
	0x0c, 0xd7, 0xd4, 0x4f, 0xb9, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0xf9, 0xc7, 0x6a, 0x33, 0xd4,
	0x05, 0x00, 0x00,
}
