// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ios/ios.proto

/*
Package ios is a generated protocol buffer package.

It is generated from these files:
	ios/ios.proto

It has these top-level messages:
	PurchaseRequest
	PurchaseReply
*/
package ios

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PurchaseRequest struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *PurchaseRequest) Reset()                    { *m = PurchaseRequest{} }
func (m *PurchaseRequest) String() string            { return proto.CompactTextString(m) }
func (*PurchaseRequest) ProtoMessage()               {}
func (*PurchaseRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PurchaseRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type PurchaseReply struct {
	Success string `protobuf:"bytes,1,opt,name=success" json:"success,omitempty"`
}

func (m *PurchaseReply) Reset()                    { *m = PurchaseReply{} }
func (m *PurchaseReply) String() string            { return proto.CompactTextString(m) }
func (*PurchaseReply) ProtoMessage()               {}
func (*PurchaseReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PurchaseReply) GetSuccess() string {
	if m != nil {
		return m.Success
	}
	return ""
}

func init() {
	proto.RegisterType((*PurchaseRequest)(nil), "ios.PurchaseRequest")
	proto.RegisterType((*PurchaseReply)(nil), "ios.PurchaseReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for IOS service

type IOSClient interface {
	Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error)
}

type iOSClient struct {
	cc *grpc.ClientConn
}

func NewIOSClient(cc *grpc.ClientConn) IOSClient {
	return &iOSClient{cc}
}

func (c *iOSClient) Purchase(ctx context.Context, in *PurchaseRequest, opts ...grpc.CallOption) (*PurchaseReply, error) {
	out := new(PurchaseReply)
	err := grpc.Invoke(ctx, "/ios.IOS/Purchase", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for IOS service

type IOSServer interface {
	Purchase(context.Context, *PurchaseRequest) (*PurchaseReply, error)
}

func RegisterIOSServer(s *grpc.Server, srv IOSServer) {
	s.RegisterService(&_IOS_serviceDesc, srv)
}

func _IOS_Purchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IOSServer).Purchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ios.IOS/Purchase",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IOSServer).Purchase(ctx, req.(*PurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _IOS_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ios.IOS",
	HandlerType: (*IOSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Purchase",
			Handler:    _IOS_Purchase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ios/ios.proto",
}

func init() { proto.RegisterFile("ios/ios.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcd, 0xcc, 0x2f, 0xd6,
	0xcf, 0xcc, 0x2f, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0xcc, 0x2f, 0x96, 0x92,
	0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f,
	0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x83, 0x2a, 0x51, 0x52, 0xe5, 0xe2, 0x0f, 0x28, 0x2d, 0x4a, 0xce,
	0x48, 0x2c, 0x4e, 0x0d, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0x49,
	0x2c, 0x49, 0x94, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x34, 0xb9, 0x78, 0x11,
	0xca, 0x0a, 0x72, 0x2a, 0x85, 0x24, 0xb8, 0xd8, 0x8b, 0x4b, 0x93, 0x93, 0x53, 0x8b, 0x8b, 0xa1,
	0xea, 0x60, 0x5c, 0xa3, 0x08, 0x2e, 0x66, 0x4f, 0xff, 0x60, 0xa1, 0x40, 0x2e, 0x0e, 0x98, 0x0e,
	0x21, 0x11, 0x3d, 0x90, 0x9b, 0xd0, 0xec, 0x91, 0x12, 0x42, 0x13, 0x2d, 0xc8, 0xa9, 0x54, 0x92,
	0x6e, 0xba, 0xfc, 0x64, 0x32, 0x93, 0xa8, 0x92, 0x80, 0x7e, 0x99, 0x21, 0xc8, 0x23, 0xba, 0x05,
	0x50, 0x69, 0x2b, 0x46, 0x2d, 0x27, 0x85, 0x28, 0xb9, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd,
	0xe4, 0xfc, 0x5c, 0xfd, 0x52, 0x03, 0x63, 0x03, 0x43, 0x63, 0x43, 0x43, 0x23, 0xfd, 0xe2, 0x62,
	0xdd, 0x82, 0x24, 0x90, 0xea, 0x24, 0x36, 0xb0, 0xa7, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x44, 0x30, 0x30, 0xa6, 0x08, 0x01, 0x00, 0x00,
}
