// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config/config.proto

It has these top-level messages:
	TestRequest
	TestReply
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *TestReply) Reset()                    { *m = TestReply{} }
func (m *TestReply) String() string            { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()               {}
func (*TestReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*TestRequest)(nil), "config.TestRequest")
	proto.RegisterType((*TestReply)(nil), "config.TestReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SSConfig service

type SSConfigClient interface {
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
}

type sSConfigClient struct {
	cc *grpc.ClientConn
}

func NewSSConfigClient(cc *grpc.ClientConn) SSConfigClient {
	return &sSConfigClient{cc}
}

func (c *sSConfigClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := grpc.Invoke(ctx, "/config.SSConfig/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SSConfig service

type SSConfigServer interface {
	Test(context.Context, *TestRequest) (*TestReply, error)
}

func RegisterSSConfigServer(s *grpc.Server, srv SSConfigServer) {
	s.RegisterService(&_SSConfig_serviceDesc, srv)
}

func _SSConfig_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SSConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.SSConfig",
	HandlerType: (*SSConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _SSConfig_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/config.proto",
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0x4b,
	0xcb, 0x4c, 0xd7, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x22, 0x17, 0x77, 0x48, 0x6a, 0x71, 0x49, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x90, 0x10,
	0x17, 0x4b, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x98, 0xad, 0xa4,
	0xca, 0xc5, 0x09, 0x51, 0x52, 0x90, 0x53, 0x29, 0x24, 0xc1, 0xc5, 0x9e, 0x9b, 0x5a, 0x5c, 0x9c,
	0x98, 0x0e, 0x53, 0x03, 0xe3, 0x1a, 0xd9, 0x70, 0x71, 0x04, 0x07, 0x3b, 0x83, 0x4d, 0x15, 0x32,
	0xe0, 0x62, 0x01, 0x69, 0x11, 0x12, 0xd6, 0x83, 0x5a, 0x8a, 0x64, 0x87, 0x94, 0x20, 0xaa, 0x60,
	0x41, 0x4e, 0xa5, 0x12, 0x83, 0x93, 0x72, 0x94, 0x62, 0x7a, 0x66, 0x49, 0x46, 0x69, 0x92, 0x5e,
	0x72, 0x7e, 0xae, 0x7e, 0xa9, 0x81, 0xb1, 0x81, 0xa1, 0xb1, 0xa1, 0xa1, 0x91, 0x7e, 0x71, 0xb1,
	0x6e, 0x41, 0x12, 0xd4, 0xe9, 0x49, 0x6c, 0x60, 0xb7, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x32, 0xb4, 0x65, 0x07, 0xd2, 0x00, 0x00, 0x00,
}
