// Code generated by protoc-gen-go. DO NOT EDIT.
// source: config/config.proto

/*
Package config is a generated protocol buffer package.

It is generated from these files:
	config/config.proto

It has these top-level messages:
	Void
	TestRequest
	TestReply
	GetSSConfigRequest
	GetSSConfigReply
	GetSSLineListRequest
	SSLine
	GetSSLineListReply
	GetSSLineConfigRequest
	GetSSLineConfigReply
	SetPasswdRequest
*/
package config

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Void struct {
}

func (m *Void) Reset()                    { *m = Void{} }
func (m *Void) String() string            { return proto.CompactTextString(m) }
func (*Void) ProtoMessage()               {}
func (*Void) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type TestRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *TestRequest) Reset()                    { *m = TestRequest{} }
func (m *TestRequest) String() string            { return proto.CompactTextString(m) }
func (*TestRequest) ProtoMessage()               {}
func (*TestRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TestRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TestReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *TestReply) Reset()                    { *m = TestReply{} }
func (m *TestReply) String() string            { return proto.CompactTextString(m) }
func (*TestReply) ProtoMessage()               {}
func (*TestReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TestReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetSSConfigRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetSSConfigRequest) Reset()                    { *m = GetSSConfigRequest{} }
func (m *GetSSConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSSConfigRequest) ProtoMessage()               {}
func (*GetSSConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetSSConfigRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetSSConfigReply struct {
	IP     string `protobuf:"bytes,1,opt,name=IP" json:"IP,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	Method string `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	Passwd string `protobuf:"bytes,4,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *GetSSConfigReply) Reset()                    { *m = GetSSConfigReply{} }
func (m *GetSSConfigReply) String() string            { return proto.CompactTextString(m) }
func (*GetSSConfigReply) ProtoMessage()               {}
func (*GetSSConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetSSConfigReply) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *GetSSConfigReply) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *GetSSConfigReply) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetSSConfigReply) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type GetSSLineListRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetSSLineListRequest) Reset()                    { *m = GetSSLineListRequest{} }
func (m *GetSSLineListRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSSLineListRequest) ProtoMessage()               {}
func (*GetSSLineListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetSSLineListRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SSLine struct {
	Id          int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Address     string `protobuf:"bytes,3,opt,name=address" json:"address,omitempty"`
	Description string `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	Status      string `protobuf:"bytes,5,opt,name=status" json:"status,omitempty"`
}

func (m *SSLine) Reset()                    { *m = SSLine{} }
func (m *SSLine) String() string            { return proto.CompactTextString(m) }
func (*SSLine) ProtoMessage()               {}
func (*SSLine) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SSLine) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SSLine) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SSLine) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *SSLine) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SSLine) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetSSLineListReply struct {
	Error string    `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	List  []*SSLine `protobuf:"bytes,2,rep,name=list" json:"list,omitempty"`
}

func (m *GetSSLineListReply) Reset()                    { *m = GetSSLineListReply{} }
func (m *GetSSLineListReply) String() string            { return proto.CompactTextString(m) }
func (*GetSSLineListReply) ProtoMessage()               {}
func (*GetSSLineListReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetSSLineListReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetSSLineListReply) GetList() []*SSLine {
	if m != nil {
		return m.List
	}
	return nil
}

type GetSSLineConfigRequest struct {
	Token  string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	LineID int64  `protobuf:"varint,2,opt,name=lineID" json:"lineID,omitempty"`
}

func (m *GetSSLineConfigRequest) Reset()                    { *m = GetSSLineConfigRequest{} }
func (m *GetSSLineConfigRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSSLineConfigRequest) ProtoMessage()               {}
func (*GetSSLineConfigRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetSSLineConfigRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *GetSSLineConfigRequest) GetLineID() int64 {
	if m != nil {
		return m.LineID
	}
	return 0
}

type GetSSLineConfigReply struct {
	Error  string `protobuf:"bytes,1,opt,name=error" json:"error,omitempty"`
	IP     string `protobuf:"bytes,2,opt,name=IP" json:"IP,omitempty"`
	Port   string `protobuf:"bytes,3,opt,name=port" json:"port,omitempty"`
	Method string `protobuf:"bytes,4,opt,name=method" json:"method,omitempty"`
	Passwd string `protobuf:"bytes,5,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *GetSSLineConfigReply) Reset()                    { *m = GetSSLineConfigReply{} }
func (m *GetSSLineConfigReply) String() string            { return proto.CompactTextString(m) }
func (*GetSSLineConfigReply) ProtoMessage()               {}
func (*GetSSLineConfigReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetSSLineConfigReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *GetSSLineConfigReply) GetIP() string {
	if m != nil {
		return m.IP
	}
	return ""
}

func (m *GetSSLineConfigReply) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *GetSSLineConfigReply) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *GetSSLineConfigReply) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type SetPasswdRequest struct {
	Passwd string `protobuf:"bytes,1,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *SetPasswdRequest) Reset()                    { *m = SetPasswdRequest{} }
func (m *SetPasswdRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPasswdRequest) ProtoMessage()               {}
func (*SetPasswdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SetPasswdRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func init() {
	proto.RegisterType((*Void)(nil), "config.Void")
	proto.RegisterType((*TestRequest)(nil), "config.TestRequest")
	proto.RegisterType((*TestReply)(nil), "config.TestReply")
	proto.RegisterType((*GetSSConfigRequest)(nil), "config.GetSSConfigRequest")
	proto.RegisterType((*GetSSConfigReply)(nil), "config.GetSSConfigReply")
	proto.RegisterType((*GetSSLineListRequest)(nil), "config.GetSSLineListRequest")
	proto.RegisterType((*SSLine)(nil), "config.SSLine")
	proto.RegisterType((*GetSSLineListReply)(nil), "config.GetSSLineListReply")
	proto.RegisterType((*GetSSLineConfigRequest)(nil), "config.GetSSLineConfigRequest")
	proto.RegisterType((*GetSSLineConfigReply)(nil), "config.GetSSLineConfigReply")
	proto.RegisterType((*SetPasswdRequest)(nil), "config.SetPasswdRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SSConfig service

type SSConfigClient interface {
	Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error)
	GetSSConfig(ctx context.Context, in *GetSSConfigRequest, opts ...grpc.CallOption) (*GetSSConfigReply, error)
	GetSSLineList(ctx context.Context, in *GetSSLineListRequest, opts ...grpc.CallOption) (*GetSSLineListReply, error)
	GetSSLineConfig(ctx context.Context, in *GetSSLineConfigRequest, opts ...grpc.CallOption) (*GetSSLineConfigReply, error)
	SetPasswd(ctx context.Context, in *SetPasswdRequest, opts ...grpc.CallOption) (*Void, error)
}

type sSConfigClient struct {
	cc *grpc.ClientConn
}

func NewSSConfigClient(cc *grpc.ClientConn) SSConfigClient {
	return &sSConfigClient{cc}
}

func (c *sSConfigClient) Test(ctx context.Context, in *TestRequest, opts ...grpc.CallOption) (*TestReply, error) {
	out := new(TestReply)
	err := grpc.Invoke(ctx, "/config.SSConfig/Test", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSConfigClient) GetSSConfig(ctx context.Context, in *GetSSConfigRequest, opts ...grpc.CallOption) (*GetSSConfigReply, error) {
	out := new(GetSSConfigReply)
	err := grpc.Invoke(ctx, "/config.SSConfig/GetSSConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSConfigClient) GetSSLineList(ctx context.Context, in *GetSSLineListRequest, opts ...grpc.CallOption) (*GetSSLineListReply, error) {
	out := new(GetSSLineListReply)
	err := grpc.Invoke(ctx, "/config.SSConfig/GetSSLineList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSConfigClient) GetSSLineConfig(ctx context.Context, in *GetSSLineConfigRequest, opts ...grpc.CallOption) (*GetSSLineConfigReply, error) {
	out := new(GetSSLineConfigReply)
	err := grpc.Invoke(ctx, "/config.SSConfig/GetSSLineConfig", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSConfigClient) SetPasswd(ctx context.Context, in *SetPasswdRequest, opts ...grpc.CallOption) (*Void, error) {
	out := new(Void)
	err := grpc.Invoke(ctx, "/config.SSConfig/SetPasswd", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SSConfig service

type SSConfigServer interface {
	Test(context.Context, *TestRequest) (*TestReply, error)
	GetSSConfig(context.Context, *GetSSConfigRequest) (*GetSSConfigReply, error)
	GetSSLineList(context.Context, *GetSSLineListRequest) (*GetSSLineListReply, error)
	GetSSLineConfig(context.Context, *GetSSLineConfigRequest) (*GetSSLineConfigReply, error)
	SetPasswd(context.Context, *SetPasswdRequest) (*Void, error)
}

func RegisterSSConfigServer(s *grpc.Server, srv SSConfigServer) {
	s.RegisterService(&_SSConfig_serviceDesc, srv)
}

func _SSConfig_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).Test(ctx, req.(*TestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSConfig_GetSSConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSSConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).GetSSConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/GetSSConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).GetSSConfig(ctx, req.(*GetSSConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSConfig_GetSSLineList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSSLineListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).GetSSLineList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/GetSSLineList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).GetSSLineList(ctx, req.(*GetSSLineListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSConfig_GetSSLineConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSSLineConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).GetSSLineConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/GetSSLineConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).GetSSLineConfig(ctx, req.(*GetSSLineConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSConfig_SetPasswd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPasswdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSConfigServer).SetPasswd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/config.SSConfig/SetPasswd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSConfigServer).SetPasswd(ctx, req.(*SetPasswdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SSConfig_serviceDesc = grpc.ServiceDesc{
	ServiceName: "config.SSConfig",
	HandlerType: (*SSConfigServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _SSConfig_Test_Handler,
		},
		{
			MethodName: "GetSSConfig",
			Handler:    _SSConfig_GetSSConfig_Handler,
		},
		{
			MethodName: "GetSSLineList",
			Handler:    _SSConfig_GetSSLineList_Handler,
		},
		{
			MethodName: "GetSSLineConfig",
			Handler:    _SSConfig_GetSSLineConfig_Handler,
		},
		{
			MethodName: "SetPasswd",
			Handler:    _SSConfig_SetPasswd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "config/config.proto",
}

func init() { proto.RegisterFile("config/config.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 576 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x5d, 0x8f, 0xd2, 0x40,
	0x14, 0x95, 0xb6, 0xa0, 0x5c, 0x74, 0x77, 0x9d, 0xc5, 0x4d, 0xd3, 0xa0, 0xb2, 0xb3, 0xd9, 0x64,
	0x43, 0x84, 0x2e, 0x10, 0x5f, 0x7c, 0x54, 0xa3, 0xc1, 0x6c, 0x0c, 0x01, 0xe3, 0x83, 0x6f, 0x85,
	0xce, 0x76, 0x27, 0x42, 0xa7, 0x76, 0x86, 0x35, 0xfb, 0x66, 0xfc, 0x0b, 0xfe, 0x34, 0x5f, 0x7d,
	0xf4, 0x87, 0x98, 0x3b, 0xd3, 0x02, 0xe5, 0x23, 0xf1, 0x89, 0x9e, 0xb9, 0xb7, 0xf7, 0x9c, 0x39,
	0xe7, 0x52, 0x38, 0x9e, 0x8a, 0xf8, 0x9a, 0x47, 0xbe, 0xf9, 0xe9, 0x24, 0xa9, 0x50, 0x82, 0x54,
	0x0c, 0xf2, 0x1a, 0x91, 0x10, 0xd1, 0x8c, 0xf9, 0x41, 0xc2, 0xfd, 0x20, 0x8e, 0x85, 0x0a, 0x14,
	0x17, 0xb1, 0x34, 0x5d, 0xb4, 0x02, 0xce, 0x67, 0xc1, 0x43, 0x7a, 0x0a, 0xb5, 0x4f, 0x4c, 0xaa,
	0x11, 0xfb, 0xb6, 0x60, 0x52, 0x11, 0x02, 0x4e, 0x1c, 0xcc, 0x99, 0x5b, 0x6a, 0x96, 0x2e, 0xaa,
	0x23, 0xfd, 0x4c, 0xcf, 0xa1, 0x6a, 0x5a, 0x92, 0xd9, 0x1d, 0x71, 0xe1, 0xfe, 0x9c, 0x49, 0x19,
	0x44, 0x79, 0x4f, 0x0e, 0x69, 0x0b, 0xc8, 0x7b, 0xa6, 0xc6, 0xe3, 0x37, 0x9a, 0x3e, 0x1f, 0x58,
	0x87, 0xb2, 0x12, 0x5f, 0x59, 0x9c, 0x75, 0x1b, 0x40, 0xaf, 0xe1, 0xa8, 0xd0, 0x8b, 0x93, 0x0f,
	0xc0, 0x1a, 0x0c, 0xb3, 0x36, 0x6b, 0x30, 0x44, 0x29, 0x89, 0x48, 0x95, 0x6b, 0x19, 0x29, 0xf8,
	0x4c, 0x4e, 0xa0, 0x32, 0x67, 0xea, 0x46, 0x84, 0xae, 0xad, 0x4f, 0x33, 0x84, 0xe7, 0x49, 0x20,
	0xe5, 0xf7, 0xd0, 0x75, 0xcc, 0xb9, 0x41, 0xf4, 0x05, 0xd4, 0x35, 0xcf, 0x15, 0x8f, 0xd9, 0x15,
	0x5f, 0x5d, 0x73, 0xb7, 0xaa, 0x1f, 0x25, 0xa8, 0x98, 0x5e, 0x14, 0xc3, 0x43, 0x5d, 0xb5, 0x47,
	0x16, 0x0f, 0x97, 0xbe, 0x58, 0x2b, 0x5f, 0xd0, 0x8a, 0x20, 0x0c, 0x53, 0x26, 0x65, 0xa6, 0x26,
	0x87, 0xa4, 0x09, 0xb5, 0x90, 0xc9, 0x69, 0xca, 0x13, 0xb4, 0x3c, 0xd3, 0xb4, 0x7e, 0x84, 0x82,
	0xa5, 0x0a, 0xd4, 0x42, 0xba, 0x65, 0x23, 0xd8, 0x20, 0xfa, 0x31, 0x33, 0x71, 0x25, 0x18, 0xad,
	0xa9, 0x43, 0x99, 0xa5, 0xa9, 0x48, 0x73, 0xb9, 0x1a, 0x10, 0x0a, 0xce, 0x8c, 0x4b, 0x34, 0xc8,
	0xbe, 0xa8, 0xf5, 0x0e, 0x3a, 0xd9, 0x16, 0x98, 0x97, 0x47, 0xba, 0x46, 0xdf, 0xc1, 0xc9, 0x72,
	0xde, 0x7f, 0x04, 0x83, 0xba, 0x66, 0x3c, 0x66, 0x83, 0xb7, 0xfa, 0xa6, 0xf6, 0x28, 0x43, 0x68,
	0x4d, 0x7d, 0x6b, 0xd0, 0x7e, 0x69, 0x26, 0x4b, 0x6b, 0x2b, 0x4b, 0x7b, 0x67, 0x96, 0xce, 0x9e,
	0x2c, 0xcb, 0x85, 0x2c, 0x5b, 0x70, 0x34, 0x66, 0x6a, 0xa8, 0x41, 0x7e, 0x89, 0x55, 0x6f, 0x69,
	0xbd, 0xb7, 0xf7, 0xc7, 0x86, 0x07, 0xf9, 0x76, 0x91, 0x0f, 0xe0, 0xe0, 0xfe, 0x92, 0xe3, 0xdc,
	0xa1, 0xb5, 0x85, 0xf7, 0x1e, 0x17, 0x0f, 0x93, 0xd9, 0x1d, 0xf5, 0x7e, 0xfe, 0xfe, 0xfb, 0xcb,
	0xaa, 0xd3, 0x43, 0xff, 0xb6, 0x9b, 0xfd, 0xb5, 0x7c, 0xc5, 0xa4, 0x7a, 0x55, 0x6a, 0x11, 0x06,
	0xb5, 0xb5, 0xc5, 0x25, 0x5e, 0xfe, 0xf6, 0xf6, 0xe6, 0x7b, 0xee, 0xce, 0x1a, 0x12, 0x34, 0x35,
	0x81, 0x47, 0x9f, 0xac, 0x11, 0x44, 0x4c, 0xb5, 0xcd, 0x23, 0xd2, 0xc4, 0xf0, 0xa8, 0xb0, 0x06,
	0xa4, 0x51, 0x18, 0xb6, 0xb1, 0xce, 0x9e, 0xb7, 0xa7, 0x8a, 0x64, 0x67, 0x9a, 0xec, 0x29, 0x75,
	0x37, 0xc8, 0x30, 0xd8, 0x36, 0xee, 0x08, 0xf2, 0xdd, 0xc2, 0xe1, 0x46, 0xba, 0xe4, 0xd9, 0xd6,
	0xcc, 0xe2, 0xf5, 0x1a, 0x7b, 0xeb, 0xc8, 0x7a, 0xae, 0x59, 0x9f, 0x53, 0x6f, 0x17, 0xeb, 0xea,
	0x9e, 0x2f, 0xa1, 0xba, 0xcc, 0x94, 0x2c, 0x0d, 0xdb, 0x8c, 0xd9, 0x7b, 0x98, 0x57, 0xf4, 0x27,
	0xeb, 0xde, 0xeb, 0xb3, 0x2f, 0xa7, 0x11, 0x57, 0x37, 0x8b, 0x49, 0x67, 0x2a, 0xe6, 0xfe, 0xe2,
	0xb2, 0x7f, 0xd9, 0xed, 0x77, 0xbb, 0x3d, 0x5f, 0xca, 0x76, 0x32, 0xc9, 0xe8, 0x26, 0x15, 0xfd,
	0xa1, 0xeb, 0xff, 0x0b, 0x00, 0x00, 0xff, 0xff, 0xca, 0xef, 0xec, 0x7d, 0x25, 0x05, 0x00, 0x00,
}
