// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user/user.proto

/*
Package user is a generated protocol buffer package.

It is generated from these files:
	user/user.proto

It has these top-level messages:
	LoginRequest
	LoginReply
	GetRolesRequest
	GetRolesReply
*/
package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Passwd   string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
}

func (m *LoginRequest) Reset()                    { *m = LoginRequest{} }
func (m *LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()               {}
func (*LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoginReply struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *LoginReply) Reset()                    { *m = LoginReply{} }
func (m *LoginReply) String() string            { return proto.CompactTextString(m) }
func (*LoginReply) ProtoMessage()               {}
func (*LoginReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginReply) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetRolesRequest struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetRolesRequest) Reset()                    { *m = GetRolesRequest{} }
func (m *GetRolesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRolesRequest) ProtoMessage()               {}
func (*GetRolesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRolesRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type GetRolesReply struct {
	Role string `protobuf:"bytes,1,opt,name=role" json:"role,omitempty"`
}

func (m *GetRolesReply) Reset()                    { *m = GetRolesReply{} }
func (m *GetRolesReply) String() string            { return proto.CompactTextString(m) }
func (*GetRolesReply) ProtoMessage()               {}
func (*GetRolesReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetRolesReply) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*LoginReply)(nil), "user.LoginReply")
	proto.RegisterType((*GetRolesRequest)(nil), "user.GetRolesRequest")
	proto.RegisterType((*GetRolesReply)(nil), "user.GetRolesReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SSUser service

type SSUserClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error)
	GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error)
}

type sSUserClient struct {
	cc *grpc.ClientConn
}

func NewSSUserClient(cc *grpc.ClientConn) SSUserClient {
	return &sSUserClient{cc}
}

func (c *sSUserClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginReply, error) {
	out := new(LoginReply)
	err := grpc.Invoke(ctx, "/user.SSUser/Login", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sSUserClient) GetRoles(ctx context.Context, in *GetRolesRequest, opts ...grpc.CallOption) (*GetRolesReply, error) {
	out := new(GetRolesReply)
	err := grpc.Invoke(ctx, "/user.SSUser/GetRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SSUser service

type SSUserServer interface {
	Login(context.Context, *LoginRequest) (*LoginReply, error)
	GetRoles(context.Context, *GetRolesRequest) (*GetRolesReply, error)
}

func RegisterSSUserServer(s *grpc.Server, srv SSUserServer) {
	s.RegisterService(&_SSUser_serviceDesc, srv)
}

func _SSUser_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSUserServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.SSUser/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSUserServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SSUser_GetRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SSUserServer).GetRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.SSUser/GetRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SSUserServer).GetRoles(ctx, req.(*GetRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SSUser_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.SSUser",
	HandlerType: (*SSUserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _SSUser_Login_Handler,
		},
		{
			MethodName: "GetRoles",
			Handler:    _SSUser_GetRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/user.proto",
}

func init() { proto.RegisterFile("user/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0x26, 0x55, 0x1b, 0x95, 0x13, 0x50, 0xe4, 0x02, 0x2a, 0x11, 0x12, 0x60, 0x06, 0x10, 0x12,
	0x71, 0xd3, 0x2c, 0x88, 0xb1, 0x0b, 0x0c, 0x4c, 0xa9, 0x58, 0xd8, 0x12, 0xb0, 0x42, 0x84, 0xeb,
	0x33, 0xb1, 0x03, 0xea, 0xca, 0xcc, 0xc6, 0xa3, 0xf1, 0x0a, 0x3c, 0x08, 0xb2, 0x93, 0xf0, 0x53,
	0xb1, 0x58, 0xfe, 0xee, 0xbe, 0x9f, 0xbb, 0x83, 0x41, 0xa5, 0x79, 0xc9, 0xec, 0x13, 0xaa, 0x12,
	0x0d, 0x92, 0xae, 0xfd, 0x07, 0x7b, 0x39, 0x62, 0x2e, 0x38, 0x4b, 0x55, 0xc1, 0x52, 0x29, 0xd1,
	0xa4, 0xa6, 0x40, 0xa9, 0x6b, 0x0e, 0x9d, 0xc2, 0xda, 0x35, 0xe6, 0x85, 0x4c, 0xf8, 0x53, 0xc5,
	0xb5, 0x21, 0x01, 0xf4, 0xad, 0x4a, 0xa6, 0x73, 0x3e, 0xf2, 0x0e, 0xbc, 0x93, 0xd5, 0xe4, 0x1b,
	0x93, 0x1d, 0xf0, 0x55, 0xaa, 0xf5, 0xcb, 0xfd, 0xa8, 0xe3, 0x3a, 0x0d, 0xa2, 0x14, 0xa0, 0xf1,
	0x50, 0x62, 0x41, 0xb6, 0xa0, 0x67, 0xf0, 0x91, 0xcb, 0x46, 0x5e, 0x03, 0x7a, 0x0c, 0x83, 0x4b,
	0x6e, 0x12, 0x14, 0x5c, 0xb7, 0x51, 0xff, 0x13, 0x8f, 0x60, 0xfd, 0x87, 0x68, 0xfd, 0x08, 0x74,
	0x4b, 0x14, 0xed, 0x34, 0xee, 0x3f, 0x79, 0xf3, 0xc0, 0x9f, 0xcd, 0x6e, 0x34, 0x2f, 0xc9, 0x15,
	0xf4, 0x5c, 0x38, 0x21, 0xa1, 0x5b, 0xfd, 0xf7, 0x36, 0xc1, 0xe6, 0x9f, 0x9a, 0x12, 0x0b, 0xba,
	0xfb, 0xfa, 0xf1, 0xf9, 0xde, 0x19, 0xd2, 0x0d, 0xf6, 0x1c, 0xb9, 0x5b, 0x31, 0x61, 0x9b, 0x17,
	0xde, 0x29, 0x39, 0x87, 0x7e, 0x9b, 0x4c, 0xb6, 0x6b, 0xe1, 0xd2, 0xc8, 0xc1, 0x70, 0xb9, 0x6c,
	0x2d, 0x57, 0xa6, 0x87, 0xb7, 0xfb, 0x79, 0x61, 0x1e, 0xaa, 0x2c, 0xbc, 0xc3, 0x39, 0xab, 0xc6,
	0xf1, 0x38, 0x8a, 0xa3, 0x68, 0xc2, 0xb4, 0x3e, 0x53, 0x99, 0x4b, 0xc9, 0x7c, 0x77, 0xee, 0xf8,
	0x2b, 0x00, 0x00, 0xff, 0xff, 0x65, 0x5c, 0xfc, 0x81, 0xa5, 0x01, 0x00, 0x00,
}
